### ISSUE TITLE
Permanently display SlidingMenu on tablets

### ISSUE THREAD

**Issue by LeonardoDavinci** [jfeinstein10/SlidingMenu#112]
Is there any way to permanently display the menu on a big screen?

**Comment by staber** [comment]
The best way is to make your menu in a fragment.

http://developer.android.com/guide/components/fragments.html

It gives you the most control over different size layouts.

**Comment by jfeinstein10** [comment]
For this you probably wouldn't use a SlidingMenu at all because there would be nothing to slide. Instead, I would recommend setting up a dual-fragment layout in your layout-large res folder and adapting your code to handle the case where there is no SlidingMenu. All you should have to do is make the id's of the containers the same.

**Comment by LeonardoDavinci** [comment]
Thank you for your answer! Now i am using fragments, but the problem is to deactivate the sliding menu. Is there any easy way?

**Comment by staber** [comment]
Assuming you're using different id's for your phone and tablet fragments. 

R.id.menu_fragment is only present in my tablet view.

``` javascript
// customize the SlidingMenu
SlidingMenu sm = getSlidingMenu();
// customize the SherlockActionBar
ActionBar actionBar = getSupportActionBar();

// Disable slidingMenu if in tablet view
if (findViewById(R.id.menu_fragment) != null) {
    sm.setSlidingEnabled(false);     
    actionBar.setDisplayHomeAsUpEnabled(false);
} else {
    sm.setSlidingEnabled(true);     
    actionBar.setDisplayHomeAsUpEnabled(true);
}
```

**Comment by LeonardoDavinci** [comment]
Thank you, it works :)
