### ISSUE TITLE
SlidingMenu+Viewpager

### ISSUE THREAD

**Issue by rfmussa** [jfeinstein10/SlidingMenu#163]
I am using Left and Right SlidingMenus on a Viewpager. How can I independently set the Mode of each one so they can work on a viewpager?(i.e LeftSlidingMenu only opens on the firstpage, and RightSliding menu on the last)

**Comment by jfeinstein10** [comment]
Right now, you can't. It'll come eventually. That'll also probably be very confusing to the user who is on the first page and wants to get to the right menu

**Comment by rfmussa** [comment]
okay, for that situation I have an action item in the action bar to toggle the righ menu. In that case, will have to think of another solution,thanks

**Comment by sniderzero** [comment]
You could set up a listener in your activity that gets called by the last
fragment and turns the touchmode on

**Comment by hwrdprkns** [comment]
I have a pull request that allows this (#128). The pull request says Horizontal Scroll view, but actually it will work for any type of scrolling, as you choose which touch events you want to send to the view and to the SlidingMenu. 

For example, if you have touchmode fullscreen or margin, you can decide to funnel events that are close enough to the  edge of the screen to the ViewPager instead of the SlidingMenu.
