### ISSUE TITLE
WARNING: Found both android-support-v4 and android-support-v13 in the dependency list

### ISSUE THREAD

**Issue by harshamv** [jfeinstein10/SlidingMenu#167]
i imported the Lib and then imported the Demos files. Then added ABS and SlidingMenu as Libs.

I am getting the following error

WARNING: Found both android-support-v4 and android-support-v13 in the dependency list

have also posted a question on StackOverFlow
http://stackoverflow.com/questions/13732500/warning-found-both-android-support-v4-and-android-support-v13-in-the-dependency

**Comment by jfeinstein10** [comment]
This is because your ABS also has a copy of the support library. You have to get rid of one of them and then point the library to the other library. It has nothing to do with my library or ABS, just the way you set them up.

**Comment by aelnakib** [comment]
would you please explain how to do it in details? am getting the same errors

**Comment by harshamv** [comment]
i still havent been able to solve it. the sliding Menu had the v13 but in all my projects i use v4. so i guess we have to delete the v13 from the lib

**Comment by CmoaToto** [comment]
v13 includes v4. 

So if your app needs v4, remove all v4 .jar files, then include SlidingMenu (wich includes v13, wich includes v4). 

If another lib includes  v4, remove it (the v4 jar) then set the other lib including SlidingMenu (which includes v13 so includes v4).

**Comment by cwc** [comment]
SlidingMenu lists its `minSdkVersion` as 5. Shouldn't it reference the v4 support library? Per http://developer.android.com/tools/extras/support-library.html:

> The Support Package includes more than one support library. Each one has a different minimum API level. For example, one library requires API level 4 or higher, while another requires API level 13 or higher

**Comment by toulouse** [comment]
I agree.

Including v13 worries me, because the whole reason we use the support library is to make sure that our app works on legacy devices. While it's almost certain that v13 will work exactly as v4 does, I simply don't want _access_ to any of the additions in v13, because they might be used without realizing they will break on earlier platforms.

Android paranoia has served us well, and v13's inclusion in SlidingMenu overrides its usage in all other libraries, where v4 is standard. If someone really plans to use v13 - and my impression is that this is quite irregular for professional Android development - they can modify it in that direction.

Is there a good reason v13 is preferred to or necessary over v4?

**Comment by jfeinstein10** [comment]
I can remove it and readd v4

**Comment by q172107875** [comment]
So cruel, I'll kill my V4 bag by myself.
