### ISSUE TITLE
The method getSupportActionBar() is undefined for the type BaseActivity

### ISSUE THREAD

**Issue by kobari** [jfeinstein10/SlidingMenu#169]
SlidingFragmentActivity don't use SherlockActivity

**Comment by jfeinstein10** [comment]
That is because the example app is the one that is on the Play Store and depends on ABS so that it can support as many phones as possible. If you don't want to use ABS, then just use the code without those references.

**Comment by mariaka** [comment]
I have added ABS as a dependency in the properties and it still shows "getSupportActionBar is undefined :(.

**Comment by agarwlGaurav** [comment]
@mariaka Please see this http://stackoverflow.com/questions/14092919/how-to-show-sliding-menu-on-activity-launch
Create an activity like SlidingSherlockFragmentActivity.

**Comment by simonjingai** [comment]
@CodingCrow No that doesn't solve the solution. That talks about making modifications. If you read the above comments:
-  @jfeinstein10: The example app uses ABS.
-  @mariaka: She's already added ABS to the dependency list but the error still happens.

So, does anybody know how to get around this?

**Comment by kirksidlo** [comment]
@simonjingai Had any luck so far?

I just happened upon this topic while searching for a similar issue.

Are you sure that your support libraries are properly configured?

As far as I understand, getSupportActionBar() requires you to use (import) android.support.v7.app.Actionbar. If you are using the traditional android.app.ActionBar you will have issues.

Also, you need to make sure that the support library has been installed correctly (android-support-v7-appcompat.jar). 

For more information, read through the following pages:
- [Action Bar | Android Developers (official)](http://developer.android.com/guide/topics/ui/actionbar.html)
- [getSupportActionBar() is undefined for the type TaskActivity. Why?](http://stackoverflow.com/questions/17893161/getsupportactionbar-the-method-getsupportactionbar-is-undefined-for-the-type)
- [...method getSupportActionBar() is undefined for the type...](http://androiddev.orkitra.com/?p=70304)

If you did fix your issue, please reply to the post with what made it work. 

If you haven't fixed it yet, and none of my links help, reply and I can try to help you further.

**Comment by JinoBetti** [comment]
Same issue here, after removing ABS and replacing it with the Support library v_7.
I got around it by : 
- changing the styles from Sherlock to AppCompat in the res/values/styles.xml file and in the manifest
- Deleting all occurrences of SherlockActivity and replacing them by ActionBarActivity
- In the SlidingMenu Library, extending both SlidingActivity and SlidingFragmentActivity with ActionBarActivity (which extends FragmentActivity)
- using getMenuInflater() instead of getSupportMenuInflater()
  (I don't really understand why, since I'm really new to android, but it seems to work fine... I still get a couple warnings due to deprecated functions or so but it works...)
