### ISSUE TITLE
The first time menu.toggle is called the view stutters

### ISSUE THREAD

**Issue by laurencedawson** [jfeinstein10/SlidingMenu#252]
After the initial call the view works perfectly. Not sure why it happens the first time.

**Comment by jwoolston** [comment]
This is probably related to #212. In my experience after the menu has been opened a few times it gets a lot better.

**Comment by laurencedawson** [comment]
I wonder if onLayout or something is being called the first time and cached for subsequent loads.

Returning to home and going back into the app will cause the view to stutter again first time.

**Comment by jwoolston** [comment]
I have GPU profiling which supports the cache theory. The first few frames take a long time because the display lists need to be built. After that they can simply be reissued during scroll provided nothing else changes. My GPU profiling indicates that this is what is happening. 

Aside from these first few frames I have determined is that the bulk of the frame time is spent in execute calls which is the GPU drawing the display lists. Now in my case I have a lot of views (over 200) so to some extent this makes sense but at the same time, unless I misunderstand hardware layers, this should not be happening for every scroll move because its a simple translation which I thought results in executing the display list once and then translating the resulting bitmap. 

Any thoughts? I know that the scrolling code in ViewPager and SlidingMenu are pretty much identical but is it possible that the Scrolled class is somehow changing the views in such a way as to require rerendering by the GPU?

**Comment by jwoolston** [comment]
Some more information:

I noticed this becoming a problem in the latest version of my app when I switched from a version of SlidingMenu that I pulled back in June/July or so and the latest one, with no differences in what gets drawn or backend stuff. In general, profiling shows the same average drawing time and breakdowns except there are an occasional few frames which have massively long (several seconds) times. In both cases I am using hardware layers. The old version of my app reports 42MB of LayerCache while the new reports only 28MB. Again, aside from the update in SlidingMenu, no other changes.

**Comment by jwoolston** [comment]
So in my case there was a difference in some code I had added to SlidingMenu. Because I still need to optimize my views I had put a temporary snippet of code in that leaves the menu views as HARDWARE always. The initial lag is from the first rendering, and then subsequent sliding is smooth, but since I had SlidingMenu rendering to hardware layers from creation, this only happens at launch. That basically removes my input from this issue, although I believe that this is inherent to the drawing system and the only way to really keep it from being a problem is to optimize the ui hierarchy and reduce view count as much as possible.

**Comment by jfeinstein10** [comment]
Closing this one. Duplicate.

**Comment by laurencedawson** [comment]
Actually, issue 262 was a duplicate of this issue 252.

**Comment by jfeinstein10** [comment]
Well regardless I'm only keeping one around. Doesn't really matter which one
