### ISSUE TITLE
Hardware layer optimization has drawing problem with webview

### ISSUE THREAD

**Issue by Qubitium** [jfeinstein10/SlidingMenu#261]
the "Explicit use of hardware layers for smoother scrolling" patches breaks rendering for webview.

Example:

Have two fragments:

1) RIGHT: main content with webview.
2) LEFT: menu content.

LEFT is hidden by default. 

A) Load a webpage in webview in RIGHT and perform sliding menu to show LEFT. 
B) So far so good. LEFT is showing and a small portion of RIGHT is showing at the right edge.
C) Now swipe left to hide menu. 
D) Problems happens here. LEFT menu slides and hides to left which is good. But RIGHT slides into view with the "hidden" portion showing white blank. After slide completes, the "hidden" blank part of webview redraws to fix itself.

There appears to be a problem with webview drawing and hardware layers with sliding menu.

**Comment by Qubitium** [comment]
Reverting to previous source tree before the hardware layer commit  fixes the rendering issue.

**Comment by jfeinstein10** [comment]
Comment out the hardware acceleration in the manageLayers method of SlidingMenu. This seems to be the only solution since SurfaceViews don't work.

**Comment by d99101** [comment]
Hey Jeremy! I love your SlidingMenu UI component! I had this same issue as well, I was able to fix from your work around provided, thanks! I do realize your very busy, but I wanted to mention I think it would be a good idea to make this a configurable option.. instead of having to comment out the hardware acceleration in the manageLayers. Please consider this next time your working in this class. Thanks!

**Comment by appler1009** [comment]
+1 for making it as a configuration option as d99101 mentioned.

**Comment by dimitrireef** [comment]
hi i am facing same issue.. did you find a solution

**Comment by hajoxx** [comment]
Same issue as @diegomontoya .

Commenting/deleting this line fixed!: 

```
//getContent().setLayerType(layerType, null);
```
