### ISSUE TITLE
example-abs doesn't work

### ISSUE THREAD

**Issue by ErnestG** [jfeinstein10/SlidingMenu#269]
Importing example-abs and adding ABS and SM creates a problem in the SlidingSherlockFragmentActivity class.

**Comment by mrityunjay-kant** [comment]
Can you post the error you're getting?

**Comment by ErnestG** [comment]
I just downloaded the latest zip, and tried to use the "example-abs" project. I add ABS and SM, but then in SLidingSherlockFragmentActivity.java I get a couple of errors from eclipse.

``` java
    public void showAbove() {
        mHelper.showAbove();
    }
```

The method showAbove() is undefined for the type SlidingActivityHelper

``` java
    public void showBehind() {
        mHelper.showBehind();
    }
```

The method showBehind() is undefined for the type SlidingActivityHelper

``` java
    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        boolean b = mHelper.onKeyDown(keyCode, event);
        if (b) return b;
        return super.onKeyDown(keyCode, event);
    }
```

The method onKeyDown(int, KeyEvent) is undefined for the type SlidingActivityHelper

**Comment by Cospel** [comment]
Bump, I got same error! :{

**Comment by smartinick** [comment]
Same error here.... used old slidingmenu version in my app, upgraded to the current version, also getting this error... any fixes upcoming / known?

Update: actually the fix is easy: replace showAbove() with showContent() and showBehind() with showMenu(), in case you used getSlidingMenu().isBehindShowing(), replace it with getSlidingMenu().isMenuShowing()...

would be really nice if that would be documented somewhere....

**Comment by jfeinstein10** [comment]
This is not an issue with the library. Please move you questions to StackOverflow.
