### ISSUE TITLE
Android 3.1, 3.2 Support

### ISSUE THREAD

**Issue by shivakumars** [jfeinstein10/SlidingMenu#374]
Hi,

I doubt wether it supports 3.1 and 3.2 Android Versions. Why because is, i face a problem in it. What happens is, i am using a fragment for menu and it doesn't get invalidated (That is, the view doesn't get updated when i interact with it). when i close the menu and reopen it, i can see the view got updated(Invalidated) according to my interaction. Other Versions of android works well. Can u help me in this?

**Comment by shivakumars** [comment]
More Info - I use it with Action Sherlock

**Comment by shivakumars** [comment]
Hey, 

I guess i fixed by making the "manageLayers()" in SlidingMenu.java that had targetapi as HoneyComb and minimum SDKINT as 11 to targetapi as ICS and minimum SDKINT as 14. Is this is a good solution? Will that create any problem? Whats ur point in this?

**Comment by jwoolston** [comment]
All this will do is not use hardware layers in Honeycomb, so it more of a problem avoidance than fix. It is possible that Honeycomb does not properly invalidate views in the same way ICS+ does. I know in that evolution in particular a lot of work was done in the area of improving the drawing system. You could add an invalidate call (preferably as specific as you can) to the end of the function you are interacting with and it should fix the problem. More intelligent drawing systems like what exists in ICS and even better, Jellybean will simply ignore any redundant calls to invalidate. Also, it has been my experience that some manufactures (most notably Samsung, and in particular with auto-invalidation) have significantly messed up the default behavior of the android drawing system, so it is something you may want to consider as well. If you have a Nexus device you can test that behavior on (or the emulator) I would to confirm it is the library/Honeycomb interaction and not a device manufacturer breaking something that was working because they want to call it their own.

**Comment by shivakumars** [comment]
thank you
