### ISSUE TITLE
Why not make a branch for SlidingMenu with action bar sherlock support?

### ISSUE THREAD

**Issue by Chrisplus** [jfeinstein10/SlidingMenu#430]
Hey, Jeremy:

Thanks for your awesome project!

But I wonder why not make a branch for SlidingMenu with action bar sherlock support? so that we could get a action-bar-version easily........

**Comment by dsdsfga** [comment]
Well there is a answer on the homepage how to setup that:
"Go into the SlidingActivities that you plan on using make them extend SherlockActivity instead of Activity. [Wrong formatting removed]"

So IMHO there is no reason to dublicate the code just for changing the super class. If you want it (like me) just change the super class.

**Comment by jfeinstein10** [comment]
^ that explanation. It's literally a 3 step process.
