### ISSUE TITLE
where is ABS

### ISSUE THREAD

**Issue by adem666** [jfeinstein10/SlidingMenu#433]
I know this question was asked million time. but, where is ABS. why it is so hard. I hope after two million asked, it will be easier

**Comment by adem666** [comment]
actionbarsherlock is full of shit. it cannot be used with slidingmenu. eclipse or actionbarsherlock has a mistaken point and it causes problem. that is when you make "clean build" sliding menu with actionbarsherlock library, actionbarsherlock library link goes incorrect state. I dont know what is wrong in actionbarsherlock. because other shity tool eclipse doesnt show any sense information

**Comment by jfeinstein10** [comment]
I really can't make it any more simple than what is in the README
-Checkout a clean copy of ActionBarSherlock and import into your Eclipse workspace.
-Add ActionBarSherlock as a dependency to SlidingMenu
-Go into the SlidingActivities that you plan on using make them extend Sherlock___Activity instead of ___Activity.
