### ISSUE TITLE
Slide contentFrame but not contentView

### ISSUE THREAD

**Issue by FreddieA** [jfeinstein10/SlidingMenu#555]
Hi, thank you very much for this library, works like a charm, i was wondering if there is a way to slide only fragments in content frame, without sliding custom tabbar(i can't use actionbar tabs)? Two images are examples of sliding menu on iOs app with TabBarViewController, i'm struggling to achieve same effect. Thanks
![img_0243blurred](https://f.cloud.github.com/assets/5392176/1370555/866fbcec-3a23-11e3-9d92-803e9679ac69.png)
![img_0244blurred](https://f.cloud.github.com/assets/5392176/1370557/8f68d496-3a23-11e3-9ad7-9ca5465fee11.png)

**Comment by abid-mujtaba** [comment]
Declare the SlidingMenu as a View declared in the XML rather than programmatically in the class. You can still access it as an object using findViewById and use it programmatically.

In your activity layout declare the topbar and then a SlidingMenu view (the project homepage has an example in the README.md). Then inside the SlidingMenu you can declare viewAbove and viewBehind layouts. Use empty FrameLayouts defined in separate layout resource files for this. Then you can add fragments to these using a FragmentTransaction.

**Comment by FreddieA** [comment]
Thank you so much!
