### ISSUE TITLE
java.lang.IllegalStateException: Both setBehindContentView must be called in onCreate in addition to setContentView.

### ISSUE THREAD

**Issue by Hikmat101** [jfeinstein10/SlidingMenu#583]
Kindly look into this.Previously app was working fine suddenly i didn't know it start crashing and crashing :@......

What could be a possible work around.

Caused by: java.lang.IllegalStateException: Both setBehindContentView must be called in onCreate in addition to setContentView.
12-13 15:41:15.534: E/AndroidRuntime(17774):    at com.slidingmenu.lib.app.SlidingActivityHelper.onPostCreate(SlidingActivityHelper.java:56)
12-13 15:41:15.534: E/AndroidRuntime(17774):    at com.slidingmenu.lib.app.SlidingFragmentActivity.onPostCreate(SlidingFragmentActivity.java:33)

**Comment by jfeinstein10** [comment]
If I were you I would follow the instructions in the error message. They were put there for a reason

**Comment by ramona-cristea** [comment]
Hello,
I see the same issue in crashlytics for my app. I looked at the activity that extends SlidingFragmentActivity and it calls both setContentView and setBehindContentView. 
Portion of code:
setContentView(getLayoutId());
setBehindContentView(generateTilesMenuList());

Even if both views are set, somehow one of the becomes null at some point I guess. Do you have any idea why this issue is happening? Devices on which crash occured: Alcatel, Panasonic, Oppo.

**Comment by Catherinelhl** [comment]
Guys! Think SlidingMenu will increasingly be used?
